# Based on https://github.com/robinlioret/gitops-promoter/blob/main/.goreleaser.yaml
project_name: gate-operator
version: 2

dist: release_dist

before:
  hooks:
    - go mod tidy
    - go mod download
    - make manifests
    - make generate
    - make build-installer IMG=ghcr.io/robinlioret/gate-operator:{{ .Tag }}

builds:
  - id: gate-operator
    main: ./cmd
    binary: gate-operator
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    goos:
      - linux
    ldflags:
      - -X github.com/robinlioret/gate-operator/common.version={{ .Version }}
      - -X github.com/robinlioret/gate-operator/common.buildDate={{ .Date }}
      - -extldflags="-static"

dockers_v2:
  - id: container
    ids:
      - gate-operator
    images:
      - ghcr.io/robinlioret/gate-operator
    tags:
      - "latest"
      - "v{{ .Version }}"
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
    platforms:
      - linux/amd64
    sbom: true

archives:
  - id: binary
    formats:
      - tar.gz
    ids:
      - "gate-operator"
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

release:
  prerelease: auto
  draft: false
  extra_files:
    - glob: ./dist/install.yaml

  header: |
    ## gate-operator
    {{ .Date }}

    ### Container images

    - ghcr.io/robinlioret/gate-operator/gate-operator:{{ .Tag }}

  footer: |
    **Full Changelog**: https://github.com/robinlioret/gate-operator/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  use:
    github
  sort: asc
  abbrev: 0
  groups: # Regex use RE2 syntax as defined here: https://github.com/google/re2/wiki/Syntax.
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 300
    - title: 'Dependency updates'
      regexp: '^.*?(feat|fix|chore)\(deps?.+\)!?:.+$'
      order: 400
    - title: 'Other work'
      order: 999

  filters:
    exclude:
      - '^test:'
      - '^skip:'
      - '^.*?Bump(\([[:word:]]+\))?.+$'