---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gate-sh-v1alpha1-gate
  failurePolicy: Fail
  name: mgate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - gate.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gates
  sideEffects: None
