# This rule is not used by the project gate-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to gate.sh resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gate-operator
    app.kubernetes.io/managed-by: kustomize
  name: gate-viewer-role
rules:
- apiGroups:
  - gate.sh
  resources:
  - gates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gate.sh
  resources:
  - gates/status
  verbs:
  - get
