apiVersion: gate.sh/v1alpha1
kind: Gate
metadata:
  labels:
    app.kubernetes.io/name: gate-operator
    app.kubernetes.io/managed-by: kustomize
  name: gate-sample
spec:
  expression:
    targetOne:
      objectRef:
        kind: Deployment
        name: coredns
        namespace: kube-system
  requeueAfter: 10s