name: Release Helm Chart to GHCR

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "version=${TAG}" >> $GITHUB_OUTPUT
          echo "Chart version: ${TAG}"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.15.1'

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart
        working-directory: ./dist/chart
        run: |
          helm package . \
            --app-version ${{ steps.version.outputs.version }} \
            --version ${{ steps.version.outputs.version }}

      - name: Push Helm chart to GHCR
        working-directory: ./dist/chart
        run: |
          CHART_FILE="gate-operator-${{ steps.version.outputs.version }}.tgz"
          OCI_URL="oci://ghcr.io/${{ github.repository }}/chart"
          
          echo "Pushing $CHART_FILE to $OCI_URL"
          helm push "$CHART_FILE" "$OCI_URL"

#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: dist/chart/gate-operator-${{ steps.version.outputs.version }}.tgz
#          generate_release_notes: true